# Generated by Django 5.0.6 on 2026-04-20 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('trabajadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vidrio', models.CharField(choices=[('normal', 'Vidrio Normal'), ('tallado', 'Vidrio Tallado'), ('espejo', 'Espejo'), ('templado', 'Templado'), ('laminado', 'Laminado')], max_length=20)),
                ('ancho', models.DecimalField(decimal_places=3, max_digits=6)),
                ('alto', models.DecimalField(decimal_places=3, max_digits=6)),
                ('area_calculada', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=8)),
                ('tipo_trabajo', models.CharField(choices=[('corte', 'Corte'), ('instalacion', 'Instalacion'), ('diseno', 'Diseno'), ('corte_instalacion', 'Corte + Instalacion')], max_length=30)),
                ('descripcion', models.TextField(blank=True)),
                ('ciudad_entrega', models.CharField(blank=True, max_length=100)),
                ('es_envio_nacional', models.BooleanField(default=False)),
                ('precio_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('cotizado', 'Cotizado'), ('abonado', 'Abonado'), ('en_proceso', 'En Proceso'), ('terminado', 'Terminado'), ('cancelado', 'Cancelado')], default='cotizado', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='clientes.cliente')),
                ('trabajador_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='trabajadores.trabajador')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
