# Generated by Django 5.0.6 on 2026-04-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPrecios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Principal', max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('precio_vidrio_normal_m2', models.DecimalField(decimal_places=2, default=25000, max_digits=10)),
                ('precio_vidrio_tallado_m2', models.DecimalField(decimal_places=2, default=45000, max_digits=10)),
                ('precio_espejo_m2', models.DecimalField(decimal_places=2, default=35000, max_digits=10)),
                ('precio_vidrio_templado_m2', models.DecimalField(decimal_places=2, default=80000, max_digits=10)),
                ('precio_vidrio_laminado_m2', models.DecimalField(decimal_places=2, default=65000, max_digits=10)),
                ('recargo_instalacion', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('recargo_diseno', models.DecimalField(decimal_places=2, default=30, max_digits=5)),
                ('costo_transporte_local', models.DecimalField(decimal_places=2, default=15000, max_digits=10)),
                ('costo_transporte_nacional', models.DecimalField(decimal_places=2, default=80000, max_digits=10)),
                ('area_minima_m2', models.DecimalField(decimal_places=3, default=0.25, max_digits=6)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuracion de Precios',
            },
        ),
    ]
