# Generated by Django 5.0.6 on 2026-04-20 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_material', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('cantidad', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('unidad', models.CharField(choices=[('m2', 'Metros cuadrados'), ('unidad', 'Unidades'), ('kg', 'Kilogramos'), ('litros', 'Litros'), ('metros', 'Metros lineales')], max_length=20)),
                ('stock_minimo', models.DecimalField(decimal_places=3, default=5, max_digits=10)),
                ('precio_compra', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ubicacion', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveedores.proveedor')),
            ],
            options={
                'ordering': ['tipo_material'],
            },
        ),
    ]
