# Generated by Django 5.0.6 on 2026-04-20 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_pago', models.DateField()),
                ('tipo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('nequi', 'Nequi'), ('daviplata', 'Daviplata'), ('otro', 'Otro')], default='efectivo', max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='clientes.cliente')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='pedidos.pedido')),
            ],
            options={
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
