# Generated by Django 5.0.6 on 2026-04-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('contacto', models.CharField(blank=True, max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('tipo_material', models.CharField(max_length=200)),
                ('notas', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
